server:
  port: 9000
spring:
  application:
    name: mima
  datasource:
    url: jdbc:mysql://localhost:3306/db_mima?useSSL=false
    username: mima
    password: password-mima
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
  show-sql: true
security:
  oauth2:
    resource:
      token-type: Bearer
      id: USER_ADMIN_RESOURCE

swagger:
  api:
    version: 1.0

check-user-scopes: true